PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/83f6c9420910be20d4f05bf35f7a7a4410e9ab28

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/a96d05c286fc1c619111f220e500b14e18c0509c) in current PX4/master (e2e72fd81e2f02c28a786e9fb5099284d0f3bd3e)
https://github.com/PX4/NuttX/compare/a96d05c286fc1c619111f220e500b14e18c0509c...83f6c9420910be20d4f05bf35f7a7a4410e9ab28

83f6c94209 (HEAD, origin/master) telnet.c: td_offset had been uint8_t. TELNET_RXBUFFER_SIZE over 256 had been broken.
e21dd68755 mmcsd_sdio:Fix breakage from 997d4 SD not functional
1d97b2ecee stack check: Support Stack Smashing Protector(SSP)
f5912b5cba arch: samd5e5 : Oneshot, freerun and tickless available support. All support runs on Timer/Counter (TC). Some fixes in external interrupt controller (EIC) and clockconfig.
171cc38ac2 arch: samd5e5 : Add watchdog timer drivers.
a7a81b5126 libc: Replace all [nx]sem_xxx with _SEM_XXX
8db91a7974 timers/timer.c:397:19: Fix warning: implicit declaration of function 'timer_setcallback'
3d0cdc3d95 sim/loadable: Remove CONFIG_USERMAIN_STACKSIZE from defconfig
6176e33ed2 fs/littlefs: enable the low level log only on debug mode
b89737395b vfs/epoll: add epoll_create1(2) implement

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/78e8090842bbd3123a58629e94d30144954f6ef4

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/95e105548a2037f42bf2f13b214ae083b921ff03) in current PX4/master (e2e72fd81e2f02c28a786e9fb5099284d0f3bd3e)
https://github.com/PX4/NuttX-apps/compare/95e105548a2037f42bf2f13b214ae083b921ff03...78e8090842bbd3123a58629e94d30144954f6ef4

78e80908 (HEAD -> master, origin/master) examples: wget: Fix nxstyle issues
10386cf5 examples/wget: wget example to work without NSH_NETINIT config
7a1d6265 netutils/webclient: Enable to send long HTTP request
18158ed2 system: add libuv port for NuttX
74c506b4 nsh: Don't check CONFIG_NFILE_STREAMS for mkdir/rename/rmdir/fs_unlink
e71e537e ftpc_transfer.c:667:15: Fix error: ‘argc’ undeclared
aaa198f0 interpreters/duktape: Clean objects
08c59984 graphics/lvgl: Specific LVGL version by kconfig
7099bc4b interpreters/duktape: Add console/print/alart support
efeb1d10 netutils/ftpc: Change watchdog callback prototype